default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog-app_development
  username: postgres
  password: Martial@5009


test:
  <<: *default
  database: blog-app_test

production:
  <<: *default
  database: blog-app_production
  username: blog-app
  password: <%= ENV["BLOG-APP_DATABASE_PASSWORD"] %>
