default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog-app_development
  #username: <%= ENV.fetch("DATABASE_USERNAME") {'postgres'} %>
  #password: <%= ENV.fetch("DATABASE_PASSWORD") {'postgres'} %>
  username: postgres
  password: Eduardo1!@
  host: localhost

 
test:
  <<: *default
  database: blog-app_test
  username: postgres
  password: Eduardo1!@
  host: localhost

production:
  <<: *default
  database: blog-app_production
  username: blog-app
  password: <%= ENV["BLOG-APP_DATABASE_PASSWORD"] %>