default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog-app_development
  user: postgres
  password: postgres

 
test:
  <<: *default
  database: blog-app_test
  user: postgres
  password: postgres

production:
  <<: *default
  database: blog-app_production
  username: blog-app
  password: <%= ENV["BLOG-APP_DATABASE_PASSWORD"] %>